apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/egedsoft/pacman-tanzu.git
    targetRevision: HEAD
    path: deployments
  destination:
    server: https://kubernetes.default.svc
    namespace: pacman
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
       selfHeal: true
       prune: true